# Generated by Django 3.1.4 on 2020-12-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achieve',
            old_name='one',
            new_name='a1',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='ten',
            new_name='a10',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='two',
            new_name='a2',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='three',
            new_name='a3',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='four',
            new_name='a4',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='five',
            new_name='a5',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='six',
            new_name='a6',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='seven',
            new_name='a7',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='eight',
            new_name='a8',
        ),
        migrations.RenameField(
            model_name='achieve',
            old_name='nine',
            new_name='a9',
        ),
    ]
