# Generated by Django 3.1.4 on 2020-12-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathed', '0002_auto_20201220_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
