from django.db import models

# Create your models here.

class user(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='user_id')
    date_created = models.CharField(max_length=225)
    username = models.CharField(max_length=225)
    password = models.CharField(max_length=225)
    first_name = models.CharField(max_length=225)
    last_name = models.CharField(max_length=225)
    age = models.CharField(max_length=225)
    mail = models.CharField(max_length=225)
    profile_pic = models.CharField(max_length=225)
    in_charge = models.CharField(max_length=225)
    phone = models.CharField(max_length=225)
    score = models.CharField(max_length=225)
    avg_1 = models.CharField(max_length=225)
    avg_2 = models.CharField(max_length=225)
    avg_3 = models.CharField(max_length=225)
    avg_4 = models.CharField(max_length=225)

class achieve(models.Model):
    username = models.CharField(max_length=225)
    one = models.CharField(max_length=225)
    two = models.CharField(max_length=225)
    three = models.CharField(max_length=225)
    four = models.CharField(max_length=225)
    five = models.CharField(max_length=225)
    six = models.CharField(max_length=225)
    seven = models.CharField(max_length=225)
    eight = models.CharField(max_length=225)
    nine = models.CharField(max_length=225)
    ten = models.CharField(max_length=225)

class test(models.Model):
    username = models.CharField(max_length=225)
    q1 = models.CharField(max_length=225)
    q2 = models.CharField(max_length=225)
    q3 = models.CharField(max_length=225)
    q4 = models.CharField(max_length=225)
    q5 = models.CharField(max_length=225)
    q6 = models.CharField(max_length=225)
    q7 = models.CharField(max_length=225)
    q8 = models.CharField(max_length=225)
    q9 = models.CharField(max_length=225)
    q10 = models.CharField(max_length=225)
    q11 = models.CharField(max_length=225)
    q12 = models.CharField(max_length=225)
    q13 = models.CharField(max_length=225)
    q14 = models.CharField(max_length=225)
    q15 = models.CharField(max_length=225)
    q16 = models.CharField(max_length=225)
    q17 = models.CharField(max_length=225)
    q18 = models.CharField(max_length=225)
    q19 = models.CharField(max_length=225)
    q20 = models.CharField(max_length=225)
    q21 = models.CharField(max_length=225)
    q22 = models.CharField(max_length=225)
    q23 = models.CharField(max_length=225)
    q24 = models.CharField(max_length=225)
    q25 = models.CharField(max_length=225)

class school(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='s_id')
    date_created = models.CharField(max_length=225)
    name = models.CharField(max_length=225)
    responsable = models.CharField(max_length=225)
    contact = models.CharField(max_length=225)
    groups_id_in_school = models.CharField(max_length=225)
    optional_password = models.CharField(max_length=225)

class school_group(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='group_id')
    users_id_array = models.CharField(max_length=225)
    school = models.CharField(max_length=225)
    group_avg = models.CharField(max_length=225)

class supervisor(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='super_id')
    username = models.CharField(max_length=225)
    password = models.CharField(max_length=225)
    date_created = models.CharField(max_length=225)
    supervising = models.CharField(max_length=225)
    first_name = models.CharField(max_length=225)
    last_name = models.CharField(max_length=225)
    mail = models.CharField(max_length=225)
    phone = models.CharField(max_length=225)